branchName: full
autoCloseIssue: true
branches:
  - label: Authentication
    name: authentication
  - label: Home 
    name: home
  - label: Project
    name: projects-service
  - label: Routes-Devops-etc
    name: routes-devops-etc

